### ISSUE TITLE
Менять уровень логирования приложения без изменения кода

### ISSUE THREAD

**Issue by EvilBeaver** [oscript-library/logos#1]
Мы опирались на log4j. Нужно идти дальше. В лог4дж есть конфиг, переключаюший уровни логов во время работы приложения. Мы же правим исходники.

**Comment by artbear** [comment]
Вполне можно.
Будем опираться на json-формат или хмл?

**Comment by EvilBeaver** [comment]
На java.properties

**Comment by artbear** [comment]
@EvilBeaver Расшифруй, что ты под этим понимаешь?
Вот прямо этот формат и будем реализовывать?

**Comment by EvilBeaver** [comment]
Он уже реализован, по сути. В читателе oscrolt.cfg
