### ISSUE TITLE
Возможность указывать произвольный путь к файлу настройки логирования logos.cfg

### ISSUE THREAD

**Issue by artbear** [oscript-library/logos#11]
Не всегда удобно располагать logos.cfg рядом с запускаемым/стартовым скриптом.
Сценарии:

- для тестов часто нужно временно включить полные логи
- для CI также удобно включать полные логи
- часто настройки проекта хранятся не в корне проекта, а в специальной вложенной папке

**Comment by EvilBeaver** [comment]
Для этого есть переменная окружения LOGOS_CONFIG. И файл не нужен.

перед запуском проблемного приложения
``set LOGOS_CONFIG=logger.rootLogger=DEBUG``
