### ISSUE TITLE
Запрещены пустые строки в файле конфигурации

### ISSUE THREAD

**Issue by artbear** [oscript-library/logos#13]
Неверный пример в разделе доки "Настройка способа вывода (класс appender)"
```
### Настройка способа вывода (класс appender)

    logger.oscript.lib.v8runner=DEBUG, v8rdebug, console
    appender.v8rdebug=ВыводЛогаВФайл
    appender.v8rdebug.file=/var/log/v8runner-debug.log
    
    appender.console=ВыводЛогаВКонсоль
```

Пустая строка не разрешена, выдается ошибка.
В строке файла должно быть либо `#` либо строка c `=`

Нужно 
+ или добавить пропуск пустой строки в код
+ или исправить доку

**Comment by artbear** [comment]
Нарвался при работе с портированным в 1С logos-ом

**Comment by EvilBeaver** [comment]
Ждем пулреквесты

**Comment by artbear** [comment]
Залито в develop
