### ISSUE TITLE
Предлагаю добавить переменную среды LOGOS_CONFIG_FULL_DEBUG для включения полных отладочных логов

### ISSUE THREAD

**Issue by artbear** [oscript-library/logos#14]
Предлагаю добавить переменную среды `LOGOS_CONFIG_FULL_DEBUG` для включения полных отладочных логов
`set LOGOS_CONFIG_FULL_DEBUG=true или Истина`
т.к. 
+ существующий вариант сложно запомнить и помнить постоянно
`set LOGOS_CONFIG=logger.rootLogger=DEBUG`
  + я его очень часто юзаю (вы же знаете мою любовь к логам), но и мне приходится либо из истории команд доставать либо ходить на сайт логоса :(
+ он еще и документирован в 2х местах вместо одного

Предлагаемый мной вариант проще, нагляднее и запоминается легче

/cc @EvilBeaver @nixel2007

**Comment by KvestIn** [comment]
Я прям 2 руками за. Каждые раз ищу эту заветную строку.

**Comment by EvilBeaver** [comment]
Ну теперь будешь искать другую заветную строку.  Какая разница? ))

**Comment by artbear** [comment]
новая заветная строка легче в голову ложится :)

**Comment by artbear** [comment]
За меня еще один голос подали :) что видно по рейтингу ишуза

@EvilBeaver Я готов сам сделать и документировать, реально задолбало :)
Примешь ПР, когда появится?

**Comment by EvilBeaver** [comment]
> новая заветная строка легче в голову ложится :)

Ну я бы с этим сильно поспорил!

> Примешь ПР, когда появится?

Я почти все принимаю, ты же знаешь. Название переменной согласуем и вперед!

Варианты:

* set LOGOS_ROOT_LEVEL=DEBUG
* set LOGOS_LEVEL=DEBUG

**Comment by artbear** [comment]
Мне больше нравится `set LOGOS_LEVEL=DEBUG`
помнить почти ничего не нужно будет :)

**Comment by EvilBeaver** [comment]
Не возражаю. Светлые головы @dmpas и @nixel2007 может еще позовем?
