### ISSUE TITLE
Как сделать для одного приложения и одного лога (!) вывод сообщений в режиме Информация в консоль, а в режиме отладки в лог-файл?

### ISSUE THREAD

**Issue by artbear** [oscript-library/logos#15]
Как сделать для одного приложения и одного лога (!) вывод сообщений в режиме Информация в консоль, а в режиме отладки в лог-файл?

Мой сценарий: 
+ хочется запускать приложения оскрипт в обычном режиме и видеть только небольшой набор информационных сообщений, 
+ но при этом в спец.лог-файл пишутся полные логи.

Можно ли как-то это сделать при условии использовании ОДНОГО лога приложения?

/cc @EvilBeaver @nixel2007 @pumbaEO @dmpas

**Comment by EvilBeaver** [comment]
Т.е. у одного аппендера - один уровень, а у другого - другой, верно? Наверное можно что-то допилить.

**Comment by artbear** [comment]
Да, скорее всего, именно через аппендер и нужно сделать

**Comment by EvilBeaver** [comment]
Не обязательно. Аппендер - это тупой класс, его ответственность - вывести то что сказали в нужное место. Т.е. он больше про "место", а не про "что"

Нужно решать где-то ранее по цепочке вызовов, имхо.

**Comment by EvilBeaver** [comment]
Предлагаю еще раз поотвечать на вопросы"зачем" и "чтобы что"

* хочется запускать приложения оскрипт в обычном режиме и видеть только небольшой набор информационных сообщений,
* но при этом в спец.лог-файл пишутся полные логи.

**Comment by artbear** [comment]
В моем исходном сообщении есть и `зачем`, и `чтобы что`
Подробнее - Повторный запуск приложения в нужном окружении не всегда возможен и хотелось бы, чтобы где-то сохранялись полные логи

**Comment by artbear** [comment]
Народ в JAVA разруливает через `log4j.appender.ИМЯ.Threshold=debug`
Например, 
https://stackoverflow.com/questions/3382985/how-to-make-log4j-to-write-to-the-console-as-well
или https://stackoverflow.com/questions/40375817/how-to-configure-log4j-to-write-debug-messages-into-a-file-and-info-to-console
или [гугл log4j log in file and console](https://www.google.ru/search?newwindow=1&safe=active&ei=vG0mWvGjGemF6AT2yI9g&q=log4j+log+in+file+and+console&oq=log4j+in+f&gs_l=psy-ab.3.7.0j0i22i30k1l9.622862.641261.0.647465.25.16.7.2.2.0.78.988.16.16.0....0...1c.1.64.psy-ab..0.24.1010...35i39k1j0i67k1j0i203k1j33i160k1j0i13k1j0i13i30k1j0i22i10i30k1j0i13i5i30k1j0i8i13i30k1.0.B70MRei6eWM)

**Comment by artbear** [comment]
Поэтому я и поддержал твою фразу об аппендерах.

**Comment by EvilBeaver** [comment]
ну раз уж и в джава.... ок, возражений не имею

**Comment by leemuar** [comment]
Аппендеры уже давно не тупой класс. Они делают обработку сообщений и сами могут решать записывать сообщение или нет.
В monolog сделано так же: у аппендеров есть уровни, которые они обрабатывают

**Comment by artbear** [comment]
Выполнено.
