### ISSUE TITLE
Ошибка при выводе сообщения содержащего символ "%"

### ISSUE THREAD

**Issue by arkuznetsov** [oscript-library/logos#19]
При выводе сообщения содержащего символ "%" возникает ошибка вызова процедуры СтрШаблон() в методе Вывести().
Логично, что каждый вызывающий должен сам следить за содержимым сообщения и учитывать особенности logos, но для случая вызова без параметров подстановки предлагаю вместо СтрШаблон(Сообщение) выводить сообщение как оно есть.
Это избавит от необходимости рефакторинга многих библиотек и приложений, особенно в тех случаях, когда тект сообщений получается от внешних вызовов.
@nixel2007, @artbear, ваше мнение?

**Comment by nixel2007** [comment]
Поддерживаю. При реализации надо проверять незаполненность всех параметров, кроме первого.

**Comment by arkuznetsov** [comment]
@nixel2007 Т.е. всех? Есть вариант когда первого параметра подстановки нет, а другие есть?

**Comment by nixel2007** [comment]
Ну, апи вроде позволяет, значит, надо учесть.

**Comment by EvilBeaver** [comment]
А как 1С себя ведет?

**Comment by nixel2007** [comment]
@EvilBeaver @Stepa86 говорил, что тоже падает.

**Comment by EvilBeaver** [comment]
Просто такая конструкция замедлит лог, он же все-таки часто вызывается

**Comment by Stepa86** [comment]
@EvilBeaver Вызов ЗначениеЗаполнено 9 раз стоит дороже, чем 1 стрШаблон ?

**Comment by EvilBeaver** [comment]
Да нет. Просто тыщу раз проверять параметры которые в 90% всегда не передаются. Холостой ход. Весят они одинаково примерно (не заметно)

**Comment by nixel2007** [comment]
ну проверьте только первый параметр) а потом я буду говорить "я же говорил". но это будет потом :)

**Comment by Stepa86** [comment]
Кстате, проверять надо на Неопределено, а не ЗначениеЗаполнено. Пустая строка может выступать как параметр

**Comment by EvilBeaver** [comment]
Я не против обоих вариантов, склоняюсь к проверке только первого, но понимаю риски и вообще, более честно - это падать и заставлять клиента заниматься экранированием. Хотя, можно принести прозрачность в жертву удобству.

Решайте короче )

**Comment by Stepa86** [comment]
@EvilBeaver Ну для меня, как скриптописателя, будет слегка шоком, когда упадет на

```bsl
ДелайРаз();
лог.Информация("Готово на 10%");
ДелайДва();
лог.Информация("Готово на 20%");
```

**Comment by EvilBeaver** [comment]
Дык я не спорю. По идее, падать должно, только если ``%Число``, а не ``%ЧтоУгодноКромеЧисла``

**Comment by EvilBeaver** [comment]
Текущее поведение и меня вгоняет в тоску

**Comment by Stepa86** [comment]
Из СП

> Подставляет параметры в строку по номеру. 
> - Если в строке встречается символ % два раза подряд (%%), такая пара трактуется как одинарный процент, независимо от того, стоит ли сразу за ними цифра или не стоит. 
> - Если параметров недостаточно для заполнения в шаблоне параметра %N, генерируется исключительная ситуация "Недостаточно фактических параметров". 
> - Если параметров слишком много, чтобы подставить их все в шаблон, генерируется исключительная ситуация "Очень много параметров".

**Comment by artbear** [comment]
Исправлено, уже в релизе
