### ISSUE TITLE
Вопросы по настройке логов через файл или переменную окружения

### ISSUE THREAD

**Issue by artbear** [oscript-library/logos#2]
В продолжение #1 
Из доки и [блога на Г+]
(https://plus.google.com/u/0/+%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9%D0%9E%D0%B2%D1%81%D1%8F%D0%BD%D0%BA%D0%B8%D0%BD/posts/3jH4wgcS8Du?cfem=1)  непонятно:
+ как в переменной окружения задать настройки для нескольких пакетов?
+ Как и где указывать файл настройки логов?

+ в офиц.доке не задокументирована установка переменной окружения 
  + `set LOGOS_CONFIG=logger.oscript.lib.commands=DEBUG`
  + сейчас это можно понять, только посмотрев видео из Г+ :(

/cc @EvilBeaver

**Comment by artbear** [comment]
В ридми буквально написано следующее
>Конфигурирование логов
Предусмотрено изменение параметров логирования через специальный файл конфигурации, либо через переменную окружения. Независимо от способа задания настроек, формат настроек остается одинаковым.

Соответственно, ответов не вижу

**Comment by EvilBeaver** [comment]
Через файл понятно, надеюсь? В переменной пишется все то же что и в файл, только вместо переводов строк - точки с запятой.

**Comment by artbear** [comment]
все вопросы выше я не понял.
код еще не успел посмотреть.
подскажи, пожалуйста

**Comment by EvilBeaver** [comment]
Прописал в доке. Если будет непонятно, согласуем в гиттере другие формулировки.

**Comment by artbear** [comment]
@EvilBeaver я бы еще добавил явное задание `set LOGOS_CONFIG=logger.oscript.lib.commands=DEBUG` в качестве примера для большего понимания.

**Comment by artbear** [comment]
Все остальное понятно.

**Comment by artbear** [comment]
Добавил в ридми пример установки переменной окружения через командную строку
