### ISSUE TITLE
Собственный способ вывода

### ISSUE THREAD

**Issue by gep2005** [oscript-library/logos#21]
Здравствуйте! Не смог разобраться с документацией. Если ли на данный момент способ создать собственный способ вывода к имеющимся двум. Например, я хочу чтобы лог выполнения скрипта выводился на консоль, записывался в файл и по окончанию скрипта был добавлен в текст уведомления на email. На данный момент сделал следующим образом. Сделал два способа вывода (Консоль и Файл) и подключил их к логу. Так же сделал собственную раскладку и в ней, кроме форматирования вывода добавляю каждое сообщение в массив. Затем по завершении из массива в текст письма дописываю html-таблицу содержащую данные лога. Но т.к. у меня к логу подключены два способа вывода, то соответственно в массив у меня каждое сообщение попадает дважды. Можно конечно накостылить... Но хотелось бы решить красиво. Есть ли возможность либо проверять в процедуре Раскладки в какой способ вывода выводиться сообщение, либо привязать к каждому способу вывода собственную процедуру Раскладки, либо написать собственный Способ вывода?

**Comment by EvilBeaver** [comment]
Можно на код взглянуть? Так сложно рассуждать и обсуждать.

Способ создать собственный способ вывода - есть.

**Comment by gep2005** [comment]
`#Использовать yadisk
#Использовать logos
#Использовать InternetMail

Перем ЛогДляПочты;
Перем Профиль;

Процедура СоздатьПрофильИнтернетПочты()
	Профиль = Новый ИнтернетПочтовыйПрофиль;

	Профиль.АдресСервераSMTP    = "smtp.yandex.ru";
	Профиль.ПользовательSMTP    = "st**on@yandex.ru";
	Профиль.ПарольSMTP          = "****";
	Профиль.ПортSMTP			= 465;
	Профиль.ИспользоватьSSLSMTP = Истина;
КонецПроцедуры

Функция Форматировать(Знач Уровень, Знач Сообщение) Экспорт
	ТД = ТекущаяДата();
	НоваяСтрокаЛогаДляПочты = ЛогДляПочты.Добавить();
	НоваяСтрокаЛогаДляПочты.ДатаСобытия = ТД;
	НоваяСтрокаЛогаДляПочты.ТипСобытия = Уровень;
	НоваяСтрокаЛогаДляПочты.ТекстСобытия = Сообщение;
    Возврат СтрШаблон("%1: %2 - %3", ТД, УровниЛога.НаименованиеУровня(Уровень), Сообщение);
КонецФункции

Процедура ОтправитьСообщениеСЛогом()
	Сообщение = Новый ИнтернетПочтовоеСообщение;
	Сообщение.Получатели.Добавить("g***5@yandex.ru");
	Сообщение.ОбратныйАдрес.Добавить("st**on@yandex.ru");
	Сообщение.Отправитель = "st**on@yandex.ru";
	Сообщение.Тема        = "Отчет о выполнении";
	Текст =  "
		|<h3>завершено!</h3>
		|<br>Показатели: .<br><table border=""1""><caption>Логи выполнения</caption><tr><th>Дата/время события</th><th>Тип события</th><th>Текст события</th></tr>";
		
	Для Каждого Событие Из ЛогДляПочты Цикл
		Текст = Текст + "<tr><td>" + Событие.ДатаСобытия + "</td><td>" + УровниЛога.НаименованиеУровня(Событие.ТипСобытия) + "</td><td>" + Событие.ТекстСобытия + "</td></tr>";
	КонецЦикла;
	Текст = Текст + "</table>";
	
	Сообщение.Тексты.Добавить(Текст, ТипТекстаПочтовогоСообщения.HTML);

	Почта = Новый ИнтернетПочта;
	Почта.Подключиться(Профиль);
	Почта.Послать(Сообщение, , ПротоколИнтернетПочты.SMTP);
	Почта.Отключиться();
КонецПроцедуры

ЛогДляПочты = Новый ТаблицаЗначений;
ЛогДляПочты.Колонки.Добавить("ДатаСобытия");
ЛогДляПочты.Колонки.Добавить("ТипСобытия");
ЛогДляПочты.Колонки.Добавить("ТекстСобытия");

ФайлЖурнала = Новый ВыводЛогаВФайл;
ФайлЖурнала.ОткрытьФайл("C:\OneScript\logs\testmail3.log");
Консоль = Новый ВыводЛогаВКонсоль;

ЛогЯД = Логирование.ПолучитьЛог("oscript.lib.yadisk");
ЛогЯД.УстановитьРаскладку(ЭтотОбъект);
ЛогЯД.ДобавитьСпособВывода(ФайлЖурнала);
ЛогЯД.ДобавитьСпособВывода(Консоль);
ЛогЯД.УстановитьУровень(УровниЛога.Ошибка);

Лог = Логирование.ПолучитьЛог("osbackuper.app.messages");
Лог.УстановитьРаскладку(ЭтотОбъект);
Лог.ДобавитьСпособВывода(ФайлЖурнала);
Лог.ДобавитьСпособВывода(Консоль);
Лог.УстановитьУровень(УровниЛога.Отладка);
Лог.Информация("Начаты действия по сохранению архивов на ЯД и локальное хранилище");
Лог.Отладка("Включена отладка");

Лог.Информация("Настройки получены");

СоздатьПрофильИнтернетПочты();

Лог.Информация("Завершено.");

ОтправитьСообщениеСЛогом();
Лог.Закрыть();

`

**Comment by gep2005** [comment]
Форматирование съехало, но смысл я думаю должен быть понятен.
Так как:
`Лог.ДобавитьСпособВывода(ФайлЖурнала);
Лог.ДобавитьСпособВывода(Консоль);`
То при:
`Лог.УстановитьРаскладку(ЭтотОбъект);`
На каждый:
`Лог.Информация("Завершено.");`
Возникает два вызова функции Форматировать
И в результате на почту приходит лог, содержащий две строчки на каждое событие
Вот как бы создать собственный СпособВывода
Что бы можно было:
`ВыводВЛогДляПочты = Новый ВыводЛогаВМассив; //например, тут как раз мой способ вывода
Лог.ДобавитьСпособВывода(ВыводВЛогДляПочты);`
И в результате при:
`Лог.Информация("Завершено.");`
должен вызываться какой-то мой метод в который передается все параметры лога и далее я уже там могу выводить сообщение туда, куда мне нужно. Например в моем случае, добавлю в таблицу значений.
Если такая возможность есть - скажите куда смотреть, пожалуйста.

**Comment by artbear** [comment]
>Так как:
`Лог.ДобавитьСпособВывода(ФайлЖурнала);
Лог.ДобавитьСпособВывода(Консоль);`
То при:
`Лог.УстановитьРаскладку(ЭтотОбъект);`
На каждый:
`Лог.Информация("Завершено.");`
Возникает два вызова функции Форматировать
И в результате на почту приходит лог, содержащий две строчки на каждое событие

Что у тебя не так сделано!
Функция Форматировать вызывается один раз на каждое событие

Код вызова https://github.com/oscript-library/logos/blob/master/src/log.os#L156

Эта проблема была актуальна для старых версий логоса.

Какая версия logos у тебя?

**Comment by gep2005** [comment]
<?xml version="1.0" encoding="utf-8"?>
<opm-metadata xmlns="http://oscript.io/schemas/opm-metadata/1.0">
    <name>logos</name>
    <version>0.6.2</version>
    <engine-version>1.0.17</engine-version>
</opm-metadata>

**Comment by gep2005** [comment]
Я установил только что скаченный OneScript  и логос шел в комплекте. Т.е. просто обновить?

**Comment by artbear** [comment]
последняя версия 1.0.2
Обновись

**Comment by nixel2007** [comment]
Закрою. Если проблема остается, переоткройте обсуждение, пожалуйста.
