### ISSUE TITLE
Изменение стандатного формата вывода сообщений - добавление имени лога

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/logos#25]
Предлагаю добавить в стандартный вывод логов от логоса имя выводимого лога по формату:
```
LOG_LEVEL - [LOG_NAME] - LOG_ENTRY
```

С уровнем и содержимым лога все понятно, они выводятся как сейчас. в LOG_NAME выводится имя лога (то, которое передается в ПолучитьЛог при инициализации логирования), с автоматическим сворачиванием имен до ... ну 20 символов допустим.

```
oscript.lib.logos -> oscript.lib.logos
oscript.lib.vanessa-runner -> o.lib.vanessa-runner
oscript.lib.vanessa-runner-long-name -> o.l.~unner-long-name
oscript.lib.vanessa.runner.long.name -> o.l.v.r.long.name
```

Можно не жестко лимитировать длину итоговой строки, а сокращать начальные узлы лога, пока не будет что-то меньшее 20 символов или не дойдет до последнего узла лога. В этом случае
`oscript.lib.vanessa-runner-long-name -> o.l.vanessa-runner-long-name` --- oscript.lib сократилось до первых точек, а последнее имя осталось необрезанным.

**Comment by nixel2007** [comment]
Готов взять на себя реализацию, если принципиальных возражений нет.

**Comment by artbear** [comment]
@nixel2007 Интересно.

Приведи желаемый пример вывод такого лога.

`o.l.v.r.long.name Информация - Тут текст` ??
или что-то другое?

**Comment by nixel2007** [comment]
@artbear чуть наоборот.
ИНФОРМАЦИЯ - o.l.v.r.long.name - Тут текст

**Comment by EvilBeaver** [comment]
А почему бы просто не включать нужные логи и гасить ненужные?

**Comment by nixel2007** [comment]
Потому что для этого нужно как минимум знать что включить. Запустил я гитсинк, оно рухнуло. Я не знаю, где оно рухнуло, в гитсинке, в cli, в делегате, в notify или еще где. Да и имена логов этих не знаю - за ними надо в код лезть.

**Comment by khorevaa** [comment]
Я за.. сталкиваюсь с данной проблемой постоянно.

**Comment by nixel2007** [comment]
А так я хотя бы визуально их могу разделить и/или отгрепать

**Comment by khorevaa** [comment]
@nixel2007 У тебя упал гитсинк 3.0? )

**Comment by nixel2007** [comment]
@khorevaa да) но я не настоящий сварщик в трешке. даже howto еще не прочел.

**Comment by nixel2007** [comment]
Здесь это офф топик)

**Comment by artbear** [comment]
Может быть, очередным ключиком это разрулим?
По умолчанию текущий вид лога или заданный авторами.
Включаем ключ, вид лога меняется на предлагаемый @nixel2007 
?

**Comment by nixel2007** [comment]
@artbear почему страшно переключить на постоянку? какие доводы против?

**Comment by EvilBeaver** [comment]
@nixel2007 

> Потому что для этого нужно как минимум знать что включить/выключить.

А как в этих ваших Джавах вопрос решен? Мы же типа на log4j подсматривали

**Comment by nixel2007** [comment]
@EvilBeaver в openapi logger и логах сонара именно так и выводится (в openapi сокращение до принудительное до n символов физическим отрезанием слева, в сонаре - схлопывание по точкам и полное имя последнего узла)

в ванильной апачевской реализации log4j вроде вывода имени лога нет, но в я довольно часто его вижу в приложениях, так что либо его как-то можно сконфигурить, либо народ пишет свои форматтеры повально (сомневаюсь).

**Comment by EvilBeaver** [comment]
Я не понял твой камент.

**Comment by nixel2007** [comment]
@EvilBeaver который из?

**Comment by EvilBeaver** [comment]
В котором ты обескуражен.

**Comment by artbear** [comment]
>там форматтер знает какие-то данные о имени лога, имени класса, т.е. там есть доступ к некоторому хранилищу.

ну это же хорошо, разве нет?

**Comment by artbear** [comment]
>почему страшно переключить на постоянку? какие доводы против?

тут не про "страшно", а про обычного пользователя продукта - 
ему будет грустновато получать усложненный лог 
`ИНФОРМАЦИЯ - [o.l.v.r.long.name] - И вот только тут интересный для него текст`

Т.е. у нас есть 2 кейса - 
1. вывод для обычного пользователя
1. вывод для более продвинутого пользователя

А вообще я за подобное дополнение, нужно только учесть интересы "простого" использования

PS я недавно решал похожую с (2) задачу 
- и сделал вывод подробных отладочных логов отдельно от консоли, в спец.файл
- для чего в свое время и ввел в logos возможность раздельного управления уровнями лога в аппендерах.

**Comment by artbear** [comment]
А если еще форматтер время и дату добавил, то пользователю будет совсем грустно.
Нужная инфа будет далеко справа :(

**Comment by khorevaa** [comment]
@artbear Я думаю надо сделать такой вывод только для увроней отладки выше чем или равно ОТЛАДКА

**Comment by nixel2007** [comment]
это хорошо. я скорее про то, что наш форматер кроме уровня сообщения и
текста сообщение больше ничего не знает. неоткуда эту инфу брать. для
реализации этой фичи надо вводить новую версию протокола для форматеров,
как это сделали для аппендеров.

вт, 4 сент. 2018 г. в 14:32, Artur Ayukhanov <notifications@github.com>:

**Comment by EvilBeaver** [comment]
да, форматтеры добавлялись можно сказать бездумно второпях. Их бы поразвивать.
