### ISSUE TITLE
Не корректная проверка на уровень в настройках аппендера

### ISSUE THREAD

**Issue by sfaqer** [oscript-library/logos#28]
https://github.com/oscript-library/logos/blob/41b608f262e2051bbd2c787599eb1690d57f7656/src/log-options.os#L172

НовыйУровень в данном случае это структура со значениями:

```bsl
	мУровниПриоритета.Вставить("Отладка"        , 0);
	мУровниПриоритета.Вставить("Информация"     , 1);
	мУровниПриоритета.Вставить("Предупреждение" , 2);
	мУровниПриоритета.Вставить("Ошибка"         , 3);
	мУровниПриоритета.Вставить("КритичнаяОшибка", 4);
	мУровниПриоритета.Вставить("Отключить"      , 5);
```

И при попытке установить в настройках уровень "Отладка" (DEBUG), проверка на заполненность выдаёт Ложь.

**Comment by nixel2007** [comment]
Можете показать код установки настроек?

**Comment by sfaqer** [comment]
> Можете показать код установки настроек?

Устанавливаю настройки не кодом, создал файлик logos.cfg рядом со стартовым скриптом, состав файла такой:
```bash
logger.rootLogger=DEBUG

appender.v8rdebug=ВыводЛогаВФайл
appender.v8rdebug.level=DEBUG
appender.v8rdebug.file=D:\temp\log\debug.log

appender.console=ВыводЛогаВКонсоль
appender.console.level=DEBUG
```

**Comment by EvilBeaver** [comment]
У вас не объявлены аппендеры. Сразу после объявления уровня нужно указать именя аппендеров (в вашем случае v8rdebug и console.

Цитата из документации:

## Настройка журнала (класс logger)

    logger.имя_журнала=Уровень[,СпособыВывода]

* имя_журнала - это имя лога, как он описан в вызове метода Логирование.ПолучитьЛог();, например, oscript.lib.v8runner.
* СпособыВывода - это список произвольных имен способов вывода, которые привязаны к журналу. Конкретная настройка каждого из заявленных способов вывода выполняется в классе настроек appender.

Например, журнал oscript.lib.v8runner может быть настроен следующим образом:

    logger.oscript.lib.v8runner=DEBUG, v8rdebug, console

**Comment by sfaqer** [comment]
> У вас не объявлены аппендеры. Сразу после объявления уровня нужно указать именя аппендеров (в вашем случае v8rdebug и console.
> 
> Цитата из документации:
> 
> ## Настройка журнала (класс logger)
> ```
> logger.имя_журнала=Уровень[,СпособыВывода]
> ```
> * имя_журнала - это имя лога, как он описан в вызове метода Логирование.ПолучитьЛог();, например, oscript.lib.v8runner.
> * СпособыВывода - это список произвольных имен способов вывода, которые привязаны к журналу. Конкретная настройка каждого из заявленных способов вывода выполняется в классе настроек appender.
> 
> Например, журнал oscript.lib.v8runner может быть настроен следующим образом:
> 
> ```
> logger.oscript.lib.v8runner=DEBUG, v8rdebug, console
> ```

Добавил объявление, ошибка таже:

[08:26:04][Step 3/4] {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 303 / [Failed] Ожидали, что проверяемое значение (0) является ЗАПОЛНЕННЫМ.
[08:26:04][Step 3/4] Не нашли значения уровень по ключу DEBUG}

Теперь файл конфига выглядит так: 
```
logger.rootLogger=DEBUG, v8rdebug, console

appender.v8rdebug=ВыводЛогаВФайл
appender.v8rdebug.level=DEBUG
appender.v8rdebug.file=D:\temp\log\debug.log

appender.console=ВыводЛогаВКонсоль
appender.console.level=DEBUG
```
