### ISSUE TITLE
Не работает установка параметров для журналов длиной oscript.lib.configor.хххх

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/logos#29]
Собственно с толкнулся с тем что не работает установка через переменную окружения или файл конфигурации уровень отладки для журналов вида
`oscript.lib.configor.yaml` - за дополнительной точки

**Comment by nixel2007** [comment]
через переменную окружения точно должно работать. как устанавливаешь?

**Comment by khorevaa** [comment]
Да.. если логер без доп точки работает

**Comment by nixel2007** [comment]
у меня там до пяти точек. показывай, как устанавливал

**Comment by khorevaa** [comment]
`set LOGOS_CONFIG=logger.oscript.lib.yaml=DEBUG`

**Comment by khorevaa** [comment]
@khorevaa Да не работает ни тот ни тот лог! Менял в файле на разные логи! Даже когда включаешь рут-логгера все равно часть логово просто не выводится! Причем только те у кого 3 и больше точен в имени

**Comment by khorevaa** [comment]
Вроде все работает.
