### ISSUE TITLE
Не тестируется через 1testrunner

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/logos#3]
build	04-Feb-2017 16:29:11	{Модуль C:\Program Files (x86)\OneScript\lib\package-loader.os / Ошибка в строке: 48 / Невозможно загрузить модуль УровниЛога. Такой символ уже определен.}

**Comment by Khorevaa** [comment]
После последних изменений тестируется.

**Comment by Khorevaa** [comment]
После подключения библиотеки через ".." опять вылезает указанная ошибка, 
Видимо из-за того, что подключены библиотеки которые используют logos.

**Comment by Stepa86** [comment]
Думаю, что это скорее ошибка движка, нежели логоса. Если из lib.config удалить инфу о модулях, то тесты проходит. Но если потом забыть вернуть эту инфу и опубликовать, то логос перестанет работать.

**Comment by EvilBeaver** [comment]
А мне кажется тут имеет место быть подключение логосов из разных путей.
Если библиотеки будут использовать логос из единого общего каталога то
такого не должно происходить

15 Фев 2017 г. 11:37 пользователь "Антон Степанов" <notifications@github.com>
написал:

**Comment by Stepa86** [comment]
@EvilBeaver Так оно и есть. Для тестов нужно подключить локальный логос, но он использует временные файлы, а они в свою очередь используют глобальный логос. Тестраннер тоже использует временные файлы и глобальный логос. Используемые библиотеки подключаются раньше, причем при подключении классов ошибок нет, а при подключении модулей есть. https://github.com/EvilBeaver/OneScript/issues/404

Я думал, что в итоге подключается класс, который пошел на регистрацию позднее, но при тестировании логоса понял, что подключается наоборот первый.

Еще раз: начинается тестирование локального логоса, подключаются временные файлы, они подключают глобальный логос, тест начинает тестировать класс Логос и на самом деле тестирует глобальный.

@nixel2007 в гиттере говорил, что нужно использовать lib.additional , но как его использовать, куда класть и какой там формат - я не нашел описалова.

**Comment by EvilBeaver** [comment]
Не может быть разных логосов в одном процессе. Про это вчера говорили на митапе OpenSource. Проблема понятна, но пока это так, это особенность движка и я не вижу особенных предпосылок это перепиливать. В процессе 1script единое пространство имен, такое же, как в 1С. Тестировать и подключать нужно исходя из этой особенности. На текущий момент это данность, которую нужно просто иметь в виду при разработке.

**Comment by dmpas** [comment]
**концептуальный костыль**:
1. Пишу в ОС-коде `#Использовать ".."`
2. Движок видит, что в `..` лежит `packagedef` и понимает, что **этожжнеспроста**
3. Понимаем, что подключаем библиотеку саму в себе, а у нея есть имя и имя ей - имя каталога (того, что `..`, преобразованное)
4. Движок хранит загруженные библиотеки по их именам. Зарегано имя? второй раз библиотеку не пытаемся грузит (и, соответственно, не ругаемся, что там всякие модули и классы уже загружены по другому пути). Не зарегано? Грузим из того каталога, что подсунули, регаем имя.
5. Пускаем тестраннер с флагом, что тестим библиотеку. Тестраннер сначала загружает эту библиотеку, а потом уже самого себя и запускается. Итого все зависимости тестраннера подхватят тестируемый логос.

Доработки движка и тестраннера я уже набросал, нужно покритиковать саму задумку.
/cc @EvilBeaver @artbear @nixel2007

**Comment by nixel2007** [comment]
Как вариант, не требующий доработок движка и тестраннера - подключение через внешний скрипт, типа как в таске - https://github.com/nixel2007/oscript-fluent/blob/feature/tests/tasks/test.os
Вот сюда же еще в самом начале прописать `#Использовать "../."` и вроде само взлетает. Сначала регится текущий/родительский каталог, а только потом уже подключается тестраннер.

> Движок хранит загруженные библиотеки по их именам. Зарегано имя? второй раз библиотеку не пытаемся грузит (и, соответственно, не ругаемся, что там всякие модули и классы уже загружены по другому пути). Не зарегано? Грузим из того каталога, что подсунули, регаем имя.

Это вроде уже и так сейчас сделано? @EvilBeaver уверял, что кто первый стал, того и тапки.

**Comment by artbear** [comment]
Подключение через внешний скрипт  мне не очень нравится, но пользуюсь.

А вообще идея @dmpas мне нравится, будет красиво и правильно.

**Comment by nixel2007** [comment]
Да мы опять в контекст и пространство имен упираемся.
Как бы кто не ругал ноду, но у нас из-за единого глобального контекста проблем примерно столько же, как было бы из-за локального :)

**Comment by dmpas** [comment]
некрасивым в данном получается то, что мы никак не отловим ошибку, если вдруг где-то загрузится библиотека не той версии.

**Comment by EvilBeaver** [comment]
@dmpas концепт одобряю в целом. Я только про пятый пункт не понял:

> Пускаем тестраннер с флагом, что тестим библиотеку. Тестраннер сначала загружает эту библиотеку, а потом уже самого себя и запускается. Итого все зависимости тестраннера подхватят тестируемый логос.

Распиши поподробнее, о чем речь?

**Comment by dmpas** [comment]
@EvilBeaver https://github.com/dmpas/1testrunner/commit/85416acdcb80b44e464ef8ee1ddbddc378c7a62a

**Comment by artbear** [comment]
Решение есть в https://xdd.silverbulleters.org/t/problema-pri-testirovanii-asserts-biblioteka-testiruet-ne-sebya-a-versiyu-iz-standartnoj-biblioteki/1784/10

**Comment by artbear** [comment]
Проблема будет решена, когда 
+ или self-contained opm появится 
  + вроде совсем чуть осталось.
+ и/или в движок будет добавлен мой уже смерженный PR https://github.com/EvilBeaver/oscript-library/pull/176
  + я уже сейчас тестирую и разрабатываю системные библиотеки с его помощью. просто и удобно.

**Comment by nixel2007** [comment]
Self contained opm не решит проблему перегрузки библиотек

**Comment by artbear** [comment]
Вышел 19 релиз, в котором приняты мои исправления для тестирования библиотек, чьи копии есть в каталоге стандартных библиотек.
Баг закрываю в связи с его решением.

Теперь можно разрабатывать и тестить любые штатные библиотеки.
