### ISSUE TITLE
Дата события лога

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/logos#31]
Сейчас в событии лога лежит УниверсальнаяДатаВМилисекундах - как изнее получить дату. Метод `СобытиеЛога.ПолучитьВремяСобытия()`

**Comment by nixel2007** [comment]
Например, вот так:
```bsl
Дата = Дата("00010101") + (ТекущаяУниверсальнаяДатаВМиллисекундах() / 1000);
```

**Comment by khorevaa** [comment]
Может туда стоит МеткуВремени писать?

**Comment by nixel2007** [comment]
Что такое метка времени? :)

**Comment by khorevaa** [comment]
`unix timestamp`

**Comment by nixel2007** [comment]
А прикладная цель какая?

**Comment by khorevaa** [comment]
Цель быть понятными! Сейчас у меня возникли проблемы с конвертацией после получения! 
Может просто дату ? сделаем?

**Comment by nixel2007** [comment]
Универсальная дата в милисекундах была сделана для регистрации событий точнее, чем секунда. Можно добавить отдельный метод, который вернёт это время как дату с приведением к секунде. Но убирать её совсем не стоит

**Comment by khorevaa** [comment]
Тут еще проблема возникла универсальная дата имеет значение без часового пояса.. т. к ней надо еще прибавлять часовой пояс или как  Но с текущей датой она не совпадает

**Comment by nixel2007** [comment]
Универсальная дата хранит время в utc+0. На то она и универсальная :) приведение к часовому поясу надо делать отдельно.

**Comment by khorevaa** [comment]
Функции получения Часового пояса нет в oscript ))) Вот и мучайся

**Comment by nixel2007** [comment]
По идее Дата(1,1,1) уже должна возвращать дату, приведенную к текущему часовому поясу. Поэтому если к ней просто прибавить количество секунд из универсальной даты, то время должно совпасть. Или все же отличается?

**Comment by khorevaa** [comment]
Проблема конвертации решена
