### ISSUE TITLE
Параметр format для класса ВывестиВКонсоль

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/logos#34]
Предлагаю сделать настраиваемый параметр вывода данных события лога:
* `text` - вывод информации как есть в текстовом формате (по умолчанию)
* `json` - вывод информации в json формате

Предлагаемый формат `json`
`{"time":"2019-02-03T14:16:13.745Z","level":"ERROR","msg":"Вывод \n ошибка","log":"oscript.lib.oscript-tasks","prefix":"connect","корова":200,"адрес":"server.com"}`

Вывод в формате `json`  будет легко читаем другими приложениями

п.с. буду использовать в https://github.com/khorevaa/oscript-tasks

**Comment by nixel2007** [comment]
Протекла абстракция. В текущей реализации за формат сообщения отвечают форматтеры/раскладки, за вывод сообщения - аппендеры. в предложенном варианте в коммите аппендер начинает отвечать за формат вывода сообщения, что нарушает его границы ответственности.

Сама идея хорошая, но кажется, что ее можно решить по-другому - добавить стандартный форматтер (или коллекцию форматтеров), которую можно было бы легко устанавливать для лога. что-то типа:

```bsl
Лог.УстановитьРаскладку(СтандартныеРаскладки.JSON);
```

**Comment by khorevaa** [comment]
@nixel2007 Я знаю о зонах ответственности классов. Тут проблема сейчас в другом. Что в один вывод необходим один формат, в другой вывод необходим другой формат.

Для этого надо делать что-то типа `Лог.УстановитьРаскладку(СтандартныеРаскладки.JSON(), ВыводВКонсоль)` но это достаточно серьезные изменения для либы в целом. Поэтому сделал по простому..  (хотя знаю, что не очень - но отлично работает).

**Comment by nixel2007** [comment]
я уже думал на тему разделения коллекции форматеров от коллекции аппендеров, как раз поглядывая на родительский log4j.

Общая идея такая - надо дать возможность настраивать фотматеры в разрезе аппендеров.
Есть некий "общий" форматер, который работает по умолчанию для каждого аппендера. При создании/настройке аппендера должна быть возможность указать переопределяющий форматер, который будет работать для этого аппендера. В целом либа для этого готова - у нас есть независимое "событие лога", есть аппендеры и есть глобальный форматер. надо только продумать апи и способ конфигурирования из файла для таких вот точечных форматеров.

кажется, что это даже можно сделать без нарушения совместимости.

**Comment by nixel2007** [comment]
а потом дойдем до вложенных объектов-логгеров, с авторазбиением через точку и независимыми настройками...

**Comment by nixel2007** [comment]
@khorevaa я просто оооочень не хочу вводить в API методы, которые через релиз сломаются. я неделю ломал голову над API v2, пока не был уверен, что и схема ложится в текущую архитектуру и явно ломать в скором времени ничего не потребуется. Поэтому если вдруг нет времени на детальную проработку этого вопроса прямо сейчас, я бы добавил отдельный форматер в json/xml, общий для всех выводов. задачу разделения по апендерам в прикладной логике решил бы разнесением в разные логгеры (если прям очень надо). и потом сел за проработку новой схемы.
